In [3]:
import pandas as pd

### Welcome to the Apply Challenge

In [4]:
link = "https://raw.githubusercontent.com/chriszapp/datasets/main/books.csv"
books = pd.read_csv(link, nrows = 13)
books.head()

,bookID,title,authors,average_rating,isbn,isbn13,language_code,num_pages,ratings_count,text_reviews_count,publication_date,publisher
0,1,Harry Potter and the Half-Blood Prince (Harry ...,J.K. Rowling/Mary GrandPré,4.57,0439785960,9780439785969,eng,652,2095690,27591,9/16/2006,Scholastic Inc.
1,2,Harry Potter and the Order of the Phoenix (Har...,J.K. Rowling/Mary GrandPré,4.49,0439358078,9780439358071,eng,870,2153167,29221,9/1/2004,Scholastic Inc.
2,4,Harry Potter and the Chamber of Secrets (Harry...,J.K. Rowling,4.42,0439554896,9780439554893,eng,352,6333,244,11/1/2003,Scholastic
3,5,Harry Potter and the Prisoner of Azkaban (Harr...,J.K. Rowling/Mary GrandPré,4.56,043965548X,9780439655484,eng,435,2339585,36325,5/1/2004,Scholastic Inc.
4,8,Harry Potter Boxed Set Books 1-5 (Harry Potte...,J.K. Rowling/Mary GrandPré,4.78,0439682584,9780439682589,eng,2690,41428,164,9/13/2004,Scholastic

In [5]:
# Firstly, have a look at the dataset
books

,bookID,title,authors,average_rating,isbn,isbn13,language_code,num_pages,ratings_count,text_reviews_count,publication_date,publisher
0,1,Harry Potter and the Half-Blood Prince (Harry ...,J.K. Rowling/Mary GrandPré,4.57,0439785960,9780439785969,eng,652,2095690,27591,9/16/2006,Scholastic Inc.
1,2,Harry Potter and the Order of the Phoenix (Har...,J.K. Rowling/Mary GrandPré,4.49,0439358078,9780439358071,eng,870,2153167,29221,9/1/2004,Scholastic Inc.
2,4,Harry Potter and the Chamber of Secrets (Harry...,J.K. Rowling,4.42,0439554896,9780439554893,eng,352,6333,244,11/1/2003,Scholastic
3,5,Harry Potter and the Prisoner of Azkaban (Harr...,J.K. Rowling/Mary GrandPré,4.56,043965548X,9780439655484,eng,435,2339585,36325,5/1/2004,Scholastic Inc.
4,8,Harry Potter Boxed Set Books 1-5 (Harry Potte...,J.K. Rowling/Mary GrandPré,4.78,0439682584,9780439682589,eng,2690,41428,164,9/13/2004,Scholastic
5,9,"Unauthorized Harry Potter Book Seven News: ""Ha...",W. Frederick Zimmerman,3.74,0976540606,9780976540601,en-US,152,19,1,4/26/2005,Nimble Books
6,10,Harry Potter Collection (Harry Potter #1-6),J.K. Rowling,4.73,0439827604,9780439827607,eng,3342,28242,808,9/12/2005,Scholastic
7,12,The Ultimate Hitchhiker's Guide: Five Complete...,Douglas Adams,4.38,0517226952,9780517226957,eng,815,3628,254,11/1/2005,Gramercy Books
8,13,The Ultimate Hitchhiker's Guide to the Galaxy ...,Douglas Adams,4.38,0345453743,9780345453747,eng,815,249558,4080,4/30/2002,Del Rey Books
9,14,The Hitchhiker's Guide to the Galaxy (Hitchhik...,Douglas Adams,4.22,1400052920,9781400052929,eng,215,4930,460,8/3/2004,Crown
10,16,The Hitchhiker's Guide to the Galaxy (Hitchhik...,Douglas Adams/Stephen Fry,4.22,0739322206,9780739322208,eng,6,1266,253,3/23/2005,Random House Audio
11,18,The Ultimate Hitchhiker's Guide (Hitchhiker's ...,Douglas Adams,4.38,0517149257,9780517149256,eng,815,2877,195,1/17/1996,Wings Books
12,21,A Short History of Nearly Everything,Bill Bryson,4.21,076790818X,9780767908184,eng,544,248558,9396,9/14/2004,Broadway Books

In [11]:
# Mission 1: use apply to create a new column called "reviews_opinion": if the ratings is between 4.5 and 5, the reviews_opinion is "very good";
# if the rating is between 4 and 4.5, the reviews_opinion is "good"; if the rating is between 3 and 4, the reviews_opinions will be "neutral";
# if the rating is up to 3 the reviews_opinion is going to be "bad"

# Add your code here
def check_rating(
    avg_rating: int
) -> str:
    if 4.5 <= avg_rating <= 5:
        return "Very Good"
    elif 4 <= avg_rating <= 4.5:
        return "Good"
    elif 3 <= avg_rating <= 4:
        return "Neutral"
    else:
        return "Bad"

books["reviews_opinion"] = books["average_rating"].apply(lambda x: check_rating(x))
books.head()

,bookID,title,authors,average_rating,isbn,isbn13,language_code,num_pages,ratings_count,text_reviews_count,publication_date,publisher,reviews_opinion
0,1,Harry Potter and the Half-Blood Prince (Harry ...,J.K. Rowling/Mary GrandPré,4.57,0439785960,9780439785969,eng,652,2095690,27591,9/16/2006,Scholastic Inc.,Very Good
1,2,Harry Potter and the Order of the Phoenix (Har...,J.K. Rowling/Mary GrandPré,4.49,0439358078,9780439358071,eng,870,2153167,29221,9/1/2004,Scholastic Inc.,Good
2,4,Harry Potter and the Chamber of Secrets (Harry...,J.K. Rowling,4.42,0439554896,9780439554893,eng,352,6333,244,11/1/2003,Scholastic,Good
3,5,Harry Potter and the Prisoner of Azkaban (Harr...,J.K. Rowling/Mary GrandPré,4.56,043965548X,9780439655484,eng,435,2339585,36325,5/1/2004,Scholastic Inc.,Very Good
4,8,Harry Potter Boxed Set Books 1-5 (Harry Potte...,J.K. Rowling/Mary GrandPré,4.78,0439682584,9780439682589,eng,2690,41428,164,9/13/2004,Scholastic,Very Good

In [14]:
# Mission 2: using apply with a function, create a column with the number of authors per book
# (note that in the column "authors", each name of the author is divided with the character "/")

# Add your code here
def len_auteurs(
    authors: str
) -> int:
    return len(authors.split("/"))

books["num_authors"] = books["authors"].apply(len_auteurs)
books.head()

,bookID,title,authors,average_rating,isbn,isbn13,language_code,num_pages,ratings_count,text_reviews_count,publication_date,publisher,reviews_opinion,num_authors
0,1,Harry Potter and the Half-Blood Prince (Harry ...,J.K. Rowling/Mary GrandPré,4.57,0439785960,9780439785969,eng,652,2095690,27591,9/16/2006,Scholastic Inc.,Very Good,2
1,2,Harry Potter and the Order of the Phoenix (Har...,J.K. Rowling/Mary GrandPré,4.49,0439358078,9780439358071,eng,870,2153167,29221,9/1/2004,Scholastic Inc.,Good,2
2,4,Harry Potter and the Chamber of Secrets (Harry...,J.K. Rowling,4.42,0439554896,9780439554893,eng,352,6333,244,11/1/2003,Scholastic,Good,1
3,5,Harry Potter and the Prisoner of Azkaban (Harr...,J.K. Rowling/Mary GrandPré,4.56,043965548X,9780439655484,eng,435,2339585,36325,5/1/2004,Scholastic Inc.,Very Good,2
4,8,Harry Potter Boxed Set Books 1-5 (Harry Potte...,J.K. Rowling/Mary GrandPré,4.78,0439682584,9780439682589,eng,2690,41428,164,9/13/2004,Scholastic,Very Good,2

In [16]:
# Mission 3: rewrite the same task as Mission 2 using the lamdba function

# Add your code here
books["num_authors_lambda"] = books["authors"].apply(lambda x: len(x.split("/")))
books.head()

,bookID,title,authors,average_rating,isbn,isbn13,language_code,num_pages,ratings_count,text_reviews_count,publication_date,publisher,reviews_opinion,num_authors,num_authors_lambda
0,1,Harry Potter and the Half-Blood Prince (Harry ...,J.K. Rowling/Mary GrandPré,4.57,0439785960,9780439785969,eng,652,2095690,27591,9/16/2006,Scholastic Inc.,Very Good,2,2
1,2,Harry Potter and the Order of the Phoenix (Har...,J.K. Rowling/Mary GrandPré,4.49,0439358078,9780439358071,eng,870,2153167,29221,9/1/2004,Scholastic Inc.,Good,2,2
2,4,Harry Potter and the Chamber of Secrets (Harry...,J.K. Rowling,4.42,0439554896,9780439554893,eng,352,6333,244,11/1/2003,Scholastic,Good,1,1
3,5,Harry Potter and the Prisoner of Azkaban (Harr...,J.K. Rowling/Mary GrandPré,4.56,043965548X,9780439655484,eng,435,2339585,36325,5/1/2004,Scholastic Inc.,Very Good,2,2
4,8,Harry Potter Boxed Set Books 1-5 (Harry Potte...,J.K. Rowling/Mary GrandPré,4.78,0439682584,9780439682589,eng,2690,41428,164,9/13/2004,Scholastic,Very Good,2,2

In [19]:
# Mission 4: create a column "comment_ration".
# Use the columns "ratings_count" and "text_reviews_count" to calculate the percentage of how many text review per reviews are per book:
# percentage = text / reviews * 100
# Use the mathematical operations between columns

# Add your code here
books["comment_ratio"] = round((books["text_reviews_count"] / books["ratings_count"]) * 100, 2)
books.head()

,bookID,title,authors,average_rating,isbn,isbn13,language_code,num_pages,ratings_count,text_reviews_count,publication_date,publisher,reviews_opinion,num_authors,num_authors_lambda,comment_ratio
0,1,Harry Potter and the Half-Blood Prince (Harry ...,J.K. Rowling/Mary GrandPré,4.57,0439785960,9780439785969,eng,652,2095690,27591,9/16/2006,Scholastic Inc.,Very Good,2,2,1.32
1,2,Harry Potter and the Order of the Phoenix (Har...,J.K. Rowling/Mary GrandPré,4.49,0439358078,9780439358071,eng,870,2153167,29221,9/1/2004,Scholastic Inc.,Good,2,2,1.36
2,4,Harry Potter and the Chamber of Secrets (Harry...,J.K. Rowling,4.42,0439554896,9780439554893,eng,352,6333,244,11/1/2003,Scholastic,Good,1,1,3.85
3,5,Harry Potter and the Prisoner of Azkaban (Harr...,J.K. Rowling/Mary GrandPré,4.56,043965548X,9780439655484,eng,435,2339585,36325,5/1/2004,Scholastic Inc.,Very Good,2,2,1.55
4,8,Harry Potter Boxed Set Books 1-5 (Harry Potte...,J.K. Rowling/Mary GrandPré,4.78,0439682584,9780439682589,eng,2690,41428,164,9/13/2004,Scholastic,Very Good,2,2,0.40

In [23]:
# Mission 5: obtain the same result of Mission 4 using apply with a function.
# Try both methods to apply to the whole dataset and apply to selected columns

# Add your code here
def calc_pct(
    df: pd.Series,
    column_1: str,
    column_2: str,
):
    return round(
        (df[column_2] / df[column_1]) * 100,2
    )

books["comment_ratio_func"] = books.apply(
    calc_pct,
    args=(
        "ratings_count",
        "text_reviews_count"
    ), axis=1
)

books[["comment_ratio", "comment_ratio_func"]].head()

   comment_ratio  comment_ratio_func
0           1.32                1.32
1           1.36                1.36
2           3.85                3.85
3           1.55                1.55
4           0.40                0.40

In [26]:
# Mission 6: obtain the same result of Mission 5 using apply lambda
# Try both methods to apply to the whole dataset and apply to selected columns

# Add your code here
books["comment_ratio_lambda"] = books.apply(
    lambda x: round(
        (x["text_reviews_count"] / x["ratings_count"]) * 100, 2
    ), axis=1
)
books[["comment_ratio", "comment_ratio_func", "comment_ratio_lambda"]].head()

   comment_ratio  comment_ratio_func  comment_ratio_lambda
0           1.32                1.32                  1.32
1           1.36                1.36                  1.36
2           3.85                3.85                  3.85
3           1.55                1.55                  1.55
4           0.40                0.40                  0.40

In [36]:
# Mission 7: extract the year from the publication_date column. How many years of publications are recorded in this dataset? Which are them?

# Add your code here
date = books["publication_date"].str.split("/").str[-1]
lenght = len(date.unique())
year = sorted(date.unique())

print(f"We have {lenght} different years on publication date!")
print(f'From {", ".join(y for y in year)}')

We have 6 different years on publication date!
From 1996, 2002, 2003, 2004, 2005, 2006